name: 'WhiteList BlackList'

on:
  schedule:
    - cron: '0 16 * * 4' # UTC
  workflow_dispatch:

jobs:
  run_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python assets/whitelist-blacklist/main.py

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github_actions[bot]"
          git add ./assets/whitelist-blacklist/*
          git commit -m "黑白名单 AutoUpdate $(date +'%Y%m%d')"

      - name: Push changes
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
